services:
  db:
    image: bitnami/postgresql:latest
    container_name: brevly-db
    platform: linux/amd64
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=brevly
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build: .
    container_name: brevly-app
    ports:
      - 3333:3333
    restart: unless-stopped
    environment:
      - PORT=3333
      - NODE_ENV=development
      - DATABASE_URL=postgresql://docker:docker@db:5432/brevly
      - CLOUDFLARE_ACCOUNT_ID=9cd06f76159c3be027717a8aad0a1ce5
      - CLOUDFLARE_ACCESS_KEY_ID=06debfdc11f2ea44f52ba26d0dac32aa
      - CLOUDFLARE_SECRET_ACCESS_KEY=511b313e726a282b3bf4e4b955097227305cdc3b8a1f0a463daa43aad0eb60ee
      - CLOUDFLARE_BUCKET=upload-server
      - CLOUDFLARE_PUBLIC_URL=https://pub-23fcf4ea20c74b739fa0b80ab4992824.r2.dev
    volumes:
      - app:/var/lib/src
    depends_on:
      - db

volumes:
  app:
  db:
