services:
  db:
    image: bitnami/postgresql:latest
    container_name: brevly-db
    platform: linux/amd64
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=brevly
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build: .
    container_name: brevly-app
    ports:
      - 3333:3333
    restart: unless-stopped
    environment:
      - PORT=3333
      - NODE_ENV=development
      - DATABASE_URL=postgresql://docker:docker@db:5432/brevly
      - CLOUDFLARE_ACCOUNT_ID=
      - CLOUDFLARE_ACCESS_KEY_ID=
      - CLOUDFLARE_SECRET_ACCESS_KEY=
      - CLOUDFLARE_BUCKET=
      - CLOUDFLARE_PUBLIC_URL=
    volumes:
      - app:/var/lib/src
    depends_on:
      - db

volumes:
  app:
  db:
